### ISSUE TITLE
Facts endpoint not returning expected results

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/rudolf#21]
Hello we have imported datasets via the FDP-to-RDF-pipeline into the triplestore.
But the facts-endpoint is not returning the expected the content.
The triples are there at the sparql-endpoint http://data.openbudgets.eu/sparql

```
SELECT ?subject  ?predicate ?object
FROM <http://data.openbudgets.eu/resource/graph/test_budgetary_central_government_expense>
WHERE {
  ?subject ?predicate ?object
}
```
But facts is returning:
http://eis-openbudgets.iais.fraunhofer.de/api/3/cubes/test_budgetary_central_government_expense__06981/facts
```
{"status":"ok","page":0,"page_size":100,"data":[],"order":[],"cell":[],"total_fact_count":0,"fields":["administrative-classification.prefLabel","date.date","economic-classification.prefLabel","currency.currency","PREV_INICIAL","PREV_DEFINITIV","D_RECON_NETOS","RECAUDADO"]}
```

**Comment by schmaluk** [comment]
Maybe we need to refresh the cache for the facts endpoint additionally.
For refreshing the cache currently this is called:
```
php artisan cache:clear
php artisan search:load
php artisan model:load global
```
According to @HimmelStein the Facts-endpoint is required for DAM.

**Comment by larjohn** [comment]
This is the expected behavior, since the data set does not have the currency attribute. This can be verified [here](http://data.openbudgets.eu/sparql?default-graph-uri=&query=%0D%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0APREFIX+qb%3A+%3Chttp%3A%2F%2Fpurl.org%2Flinked-data%2Fcube%23%3E%0D%0APREFIX+skos%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%3E%0D%0APREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0D%0APREFIX+xro%3A+%3Chttp%3A%2F%2Fpurl.org%2Fxro%2Fns%23%3E%0D%0A%0D%0ASELECT+%3Fcurrency+WHERE+%7B%0D%0A%09%3Chttp%3A%2F%2Fdata.openbudgets.eu%2Fresource%2Fdataset%2Ftest_budgetary_central_government_expense%3E+%3Chttp%3A%2F%2Fdata.openbudgets.eu%2Fontology%2Fdsd%2Fattribute%2Fcurrency%3E++%3Fcurrency%0D%0A%7D%0D%0A%0D%0A&should-sponge=&format=text%2Fhtml&timeout=0).

We have agreed in a past technical meeting that the data-set-attached attributes would also be presented in the facts and aggregates results, the way OpenSpending does. This is the reason rudolf fails to bring back any result. The query sans the currency predicate would be: 

```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xro: <http://purl.org/xro/ns#>

SELECT ?binding_165bf ?binding_5fc73 ?binding_4be74 ?binding_1af03 ?binding_a5575 ?binding_494c6 ?binding_05d4e ?binding_72b8d ?binding_165bf_19056 ?binding_4be74_19056 ?observation WHERE {
	?observation <http://data.openbudgets.eu/ontology/dsd/test_budgetary_central_government_expense/dimension/administrative-classification> ?binding_165bf ; <http://data.openbudgets.eu/ontology/dsd/test_budgetary_central_government_expense/dimension/date> ?binding_5fc73 ; <http://data.openbudgets.eu/ontology/dsd/test_budgetary_central_government_expense/dimension/economic-classification> ?binding_4be74 ; <http://data.openbudgets.eu/ontology/dsd/test_budgetary_central_government_expense/measure/PREV_INICIAL> ?binding_a5575 ; <http://data.openbudgets.eu/ontology/dsd/test_budgetary_central_government_expense/measure/PREV_DEFINITIV> ?binding_494c6 ; <http://data.openbudgets.eu/ontology/dsd/test_budgetary_central_government_expense/measure/D_RECON_NETOS> ?binding_05d4e ; <http://data.openbudgets.eu/ontology/dsd/test_budgetary_central_government_expense/measure/RECAUDADO> ?binding_72b8d ; <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> qb:Observation ; <http://purl.org/linked-data/cube#dataSet> <http://data.openbudgets.eu/resource/dataset/test_budgetary_central_government_expense> .
	?binding_165bf <http://www.w3.org/2004/02/skos/core#prefLabel> ?binding_165bf_19056 , ?binding_165bf_19056 .
	?binding_4be74 <http://www.w3.org/2004/02/skos/core#prefLabel> ?binding_4be74_19056 , ?binding_4be74_19056 .
	FILTER (LANG (?binding_165bf_19056) = 'en' || LANG (?binding_165bf_19056) = '')
	FILTER (LANG (?binding_4be74_19056) = 'en' || LANG (?binding_4be74_19056) = '')
}
ORDER BY ASC (?observation)
LIMIT 100 OFFSET 0
```
which seems to work fine.

**Comment by marek-dudas** [comment]
So it seems to me that rudolf supports only datasets with one currency, specified with an attribute attached to the dataset, while FDPtoRDF produces datasets where currency is specified with an attribute attached to a measure property  - that is because in FDP, there can be several measures, each using different currency. I don't know rudolf at all, so please correct me if I am wrong, I am just trying to find out whether there is something that should be changed in FDPtoRDF pipeline.

**Comment by larjohn** [comment]
For Rudolf to understand the currency of a measure, there has to be a standard way. If you have an alternative way, we can accommodate this as well.
