### ISSUE TITLE
Missing prefLabel in the Rudolf API response

### ISSUE THREAD

**Issue by fathoni** [openbudgets/rudolf#6]
Apparently there is something wrong either in the dataset transformation or in the parsing of SPARQL query result. For example, when I call Aragon income economic classification [here](http://ws307.math.auth.gr/rudolf/public/api/3/cubes/aragon-2006-income__4dac3/members/economicClassification), it only lists the URI of the codelist without `notation`, `prefLabel`, and other details. However in the transformed codelist dataset itself [here](https://github.com/openbudgets/datasets/blob/master/Aragon/2006/codelist/estructura_economica_i_aragon_2006.ttl), the `notation`, `prefLabel` has already been provided. I am unsure if this is a problem in the dataset or in the Babbage. What do you think, @larjohn ?

**Comment by larjohn** [comment]
A first pointer is that the code list has not been loaded into the triple store. Actually, when rudolf builds the model, it looks for subproperties based on the values of dimensions. If no such subproperties are found, then the only attribute is the URI of the value.

Indeed, 

select ?p ?o {http://data.openbudgets.eu/resource/codelist/estructura_economica_i_aragon_2006/404013 ?p ?o}

brings no results, which means I didn't find the codelist when I loaded the dataset in the store. I will do so and then check back. Please keep in mind that in the current implementation, you will have to clear ALL your cache in order to reload this specific model. This is an improvement that has to be done. I am creating another issue for this here: #7

**Comment by larjohn** [comment]
I uploaded the codelists for Aragon 2006 in the triple store and it seems it works well. For your own deployment you will have to clear caches in order to refresh the model:

php artisan cache:clear
